### ISSUE TITLE
OpenAPI 3.0 treatment of enums

### ISSUE THREAD

**Issue by opoudjis** [nsip/specgen_input#44]
Enums with annotation are currently being output to JSONSchema as:

````
        oneOf:
        - const: "LEAInfo"
          title: LEAInfo
          ...
````

This is valid JSON Schema, but not valid OpenAPI 3.0.x JSON Schema: `const` is not recognised in its subset of JSON Schema. Until we can adopt OpenAPI 3.1.0, which complies with full JSON Schema, we need to change this to:

````
        oneOf:
        - enum: ["LEAInfo"]
          title: LEAInfo
          ...
```` 

Impact:

`Error :: spec rule :: Property `const` is not expected here.: 9589`

This accounts for 9589 of the 11398 errors reported by Redocly.
