### ISSUE TITLE
Illegal use of name property in Reponse objects

### ISSUE THREAD

**Issue by opoudjis** [nsip/specgen_input#45]
Request parameters in OpenAPI, such as components.schemas.httpHeaders.request, are defined by the Parameter object, which includes `name`.

Response parameters in OpenAPI, such as components.schemas.httpHeaders.response, are defined by the Header object, which is like the Parameter object, but excludes `name` and `in`:

> The Header Object follows the structure of the [Parameter Object](https://spec.openapis.org/oas/v3.0.3#parameterObject) with the following changes:
>
> name MUST NOT be specified, it is given in the corresponding headers map.
> in MUST NOT be specified, it is implicitly in header.

The responses given in the commonDefs files all need to drop their name fields:

e.g.

commonDefs-all-headers.yaml, components.schemas.httpHeaders.response:

````
        accept:
          name: accept
          schema:
            type: string
          description: >-
            Optional: Indicates to the caller what the provider accepts. Typical values are application/xml or application/json. Often provided when a HTTP code 415 is returned.
````

This generates the error message:

`Error :: spec rule :: Property `name` is not expected here.`: 25 times.
